# Generated by Django 4.2.16 on 2024-12-14 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthForms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('girisback', models.ImageField(blank=True, help_text='Background Image for Giris', null=True, upload_to='backgrounds/')),
                ('kayitback', models.ImageField(blank=True, help_text='Background Image for Kayit', null=True, upload_to='backgrounds/')),
                ('pargraph_login', models.TextField(help_text='Subheading for login')),
                ('pargraph_singup', models.TextField(help_text='Subheading for signup')),
            ],
        ),
    ]
