# Generated by Django 4.2.16 on 2024-12-09 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(help_text="Enter the FontAwesome or custom icon class (e.g., 'flaticon-034-stationary-bike')", max_length=100)),
            ],
        ),
    ]
