# Generated by Django 4.2.16 on 2024-12-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0003_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='upload an image for the gallery', upload_to='gallery/')),
                ('title', models.CharField(blank=True, help_text='Title of the image', max_length=100, null=True)),
                ('description', models.TextField(blank=True, help_text='Description of the image', null=True)),
            ],
        ),
    ]
