# Generated by Django 4.2.16 on 2024-12-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0004_galleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the team member', max_length=100)),
                ('role', models.CharField(help_text='Role of the team member', max_length=100)),
                ('image', models.ImageField(help_text='Upload image of the team member', upload_to='team/')),
            ],
        ),
    ]
