# Generated by Django 4.2.16 on 2024-12-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0005_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(help_text='Main Heading of  the Banner ', max_length=200)),
                ('subheading', models.TextField(help_text='subheading of the banner ')),
                ('button_text', models.CharField(help_text='Text for button', max_length=50)),
                ('button_link', models.URLField(help_text='URL the button redirects to ')),
                ('background_image', models.ImageField(help_text='Background image for the banner', upload_to='banner/')),
            ],
        ),
    ]
