# Generated by Django 4.2.16 on 2024-12-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0006_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
