# Generated by Django 4.2.16 on 2024-12-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0007_contactinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='phone',
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='phone_numbers',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
