# Generated by Django 4.2.16 on 2024-12-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0008_remove_contactinfo_phone_contactinfo_phone_numbers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hero/')),
                ('tagline', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('register_link', models.URLField()),
                ('login_link', models.URLField()),
            ],
        ),
    ]
