# Generated by Django 4.2.16 on 2024-12-14 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0009_hero'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(default='logos/default_logo.png', upload_to='logos/')),
            ],
        ),
    ]
