# Generated by Django 4.2.16 on 2024-12-14 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0010_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='title',
            field=models.CharField(default='Gym', help_text='Website Title', max_length=255),
        ),
    ]
