# Generated by Django 4.2.16 on 2024-12-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0011_sitesettings_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='login_link',
            field=models.URLField(default='http://127.0.0.1:8000/auth/'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='register_link',
            field=models.URLField(default='http://127.0.0.1:8000/auth/'),
        ),
    ]
